### ISSUE TITLE
More documentations maybe!?

### ISSUE THREAD

**Issue by mmrezaie** [zhouyan/vSMC#6]
Since I am not very good with cmake, I maybe asking too simple question but, may I ask for more information on what packages should be available in the system (like ubuntu). As far as my cmake go it generates makefile with no problem and OpenMP as available backend but when I compile the examples I get errors like these (and many more):

common.hpp:167:15: error: expected nested-name-specifier before ‘distribution_type’ using distribution_type = Name##Distribution<RealType>

aligned_memory.hpp:359:1: error: expected unqualified-id before ‘using’
 using Vector = typename std::conditional<std::is_scalar<T>::value,

Should I have done anything specific before starting to compile?

**Comment by zhouyan** [comment]
It looks like your compiler does not yet support C++11 type alias

The library now assumes full C++11 support as minimum and I am planning to move to C++14 next year.

**Comment by zhouyan** [comment]
A new release is posted with a new user guide for version 2, see
https://github.com/zhouyan/vSMC/releases/tag/v2.2.0
I can't help if you are not familiar with basic cmake and c++11. You need to seek informations else where. In fact, cmake is not required for using the library. It is only used for building examples. To use the library, simply move `include/vsmc` to wherever it should be

**Comment by mmrezaie** [comment]
Thanks, but my question was about building the examples. I will check the link you provided.

**Comment by zhouyan** [comment]
From the issue you posted, the problem is that you don't have a compiler supporting c++11. As I already said before. There's nothing I can help. You need to upgrade your compiler.
